language: go

go:
  - 1.6.2

sudo: required

services:
  - docker

install:
  - go get github.com/nsqio/nsq/...
  - go get github.com/mattn/goveralls
  - make setup

script:
  - make test-coverage

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/test-coverage-all.out -service=travis-ci
  - ./scripts/push_to_docker.sh
